owner: amblerkr
repo: apps.status

sites:
  - name: ambler.kr
    url: https://ambler.kr/
  - name: link.ambler.kr
    url: https://link.ambler.kr/

status-website:
  cname: apps.status.ambler.kr
  logoUrl: https://raw.githubusercontent.com/amblerkr/amblerkr/master/img/LOGO_trans.png
  name: Apps | Ambler Status
  introTitle: "**Upptime** for Ambler"
  introMessage: ⚡
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://go.ambler.kr/website
    - title: Discord
      href: https://go.ambler.kr/discord
